apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis-service"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:latest
        command:
          - redis-server
          - "/redis-master/redis.conf"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 6379 
          name: redis-port
        volumeMounts:
        - name: aws-pvc
          mountPath: /var/lib/redis
        - name: config-volume
          mountPath: /redis-master
      volumes:
        - name: config-volume
          configMap:
            name: redis-ss-configuration
            items:
            - key: redis-config
              path: redis.conf


  volumeClaimTemplates:
  - metadata:
      name: aws-pvc
      labels:
        type: aws-pvc
    spec:
       accessModes:
         - ReadWriteOnce
       resources:
        requests:
          storage: 1Gi
        storageClassName: gp2

